name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, lint, test and build
      run: |
        Xvfb :1 -screen 0 1280x800x24 &
        export DISPLAY=:1
        npm ci
        npm run lint
        npm run test:unit
        npm run test:e2e:headless
        npm run build --if-present
      env:
        CI: true
